package com.example.cardcharity.presentation.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF006493)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFc7e6ff)
val light_onPrimaryContainer = Color(0xFF001e30)
val light_secondary = Color(0xFF4f606e)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFd3e5f6)
val light_onSecondaryContainer = Color(0xFF0b1d29)
val light_tertiary = Color(0xFF64597b)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFebdcff)
val light_onTertiaryContainer = Color(0xFF201635)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFF5F5F8)
val light_onBackground = Color(0xFF1a1c1e)
val light_surface = Color(0xFFFFFFFF)
val light_onSurface = Color(0xFF1a1c1e)
val light_surfaceVariant = Color(0xFFdee3ea)
val light_onSurfaceVariant = Color(0xFF41474d)
val light_outline = Color(0xFF72787e)
val light_inverseOnSurface = Color(0xFFf0f0f3)
val light_inverseSurface = Color(0xFF2f3032)
val light_inversePrimary = Color(0xFF88ceff)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFF88ceff)
val dark_onPrimary = Color(0xFF00344f)
val dark_primaryContainer = Color(0xFF004b70)
val dark_onPrimaryContainer = Color(0xFFc7e6ff)
val dark_secondary = Color(0xFFb7c9d9)
val dark_onSecondary = Color(0xFF22323f)
val dark_secondaryContainer = Color(0xFF384956)
val dark_onSecondaryContainer = Color(0xFFd3e5f6)
val dark_tertiary = Color(0xFFcfc0e8)
val dark_onTertiary = Color(0xFF352b4a)
val dark_tertiaryContainer = Color(0xFF4c4162)
val dark_onTertiaryContainer = Color(0xFFebdcff)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1a1c1e)
val dark_onBackground = Color(0xFFe2e2e5)
val dark_surface = Color(0xFF16181A)
val dark_onSurface = Color(0xFFe2e2e5)
val dark_surfaceVariant = Color(0xFF41474d)
val dark_onSurfaceVariant = Color(0xFFc1c7ce)
val dark_outline = Color(0xFF8b9198)
val dark_inverseOnSurface = Color(0xFF1a1c1e)
val dark_inverseSurface = Color(0xFFe2e2e5)
val dark_inversePrimary = Color(0xFF006493)
val dark_shadow = Color(0xFF000000)

